services:
  db:
    # We aren't scaling these up, so give them prettier names.
    container_name: 'db'
    build:
      context: './docker'
      dockerfile: 'Dockerfile.postgres'
    env_file: '.env'
    volumes:
      - 'db_data:/var/lib/postgresql/data'

  dbadmin:
    container_name: 'dbadmin'
    depends_on:
      - 'db'
    # This used to (<= 4.8.0) be based on Alpine, but then PHP 7.4 was deprecated,
    # and Adminer has gone pretty unmaintained. So we settle for this image based
    # on Debian Bullseye.
    image: 'adminer:4.8.1'
    restart: 'always'
    ports:
      - '8080:8080'

  prep: &node
    container_name: 'prep'
    depends_on:
      - 'db'
    build:
      context: './docker'
      dockerfile: 'Dockerfile.pnpm'
    env_file: '.env'
    volumes:
      - '.:/home/node/app'

  home:
    <<: *node
    depends_on:
      - 'prep'
      - 'db'
    container_name: 'home'
    working_dir: '/home/node/app/home'
    command: ['pnpm', 'run', 'dev', '--host']
    ports:
      - '5173:5173'

volumes:
  db_data:
