# syntax=docker/dockerfile:1.3.0-labs
# Bump syntax version so we can use envvars in RUN statements. See:
# https://github.com/moby/buildkit/issues/815

# This Dockerfile builds an image with pnpm for development.

# Consider keeping this in sync with the other distro choices.
FROM node:21.5.0-alpine3.19

ENV PNPM_HOME="/opt/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

USER node
WORKDIR /home/node/app
