#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER "$POSTGRES_USER_HOME" WITH PASSWORD '$POSTGRES_PASSWORD_HOME';
	GRANT "admin" TO "$POSTGRES_USER_HOME";
EOSQL
