name: 'Build and Deploy'
on:
  push:
    branches:
      - 'main'
jobs:
  build_deploy:
    runs-on: 'ubuntu-22.04'
    strategy:
      matrix:
        image:
          [
            { dockerfile: 'Dockerfile.pnpm', target: 'prep' },
            { dockerfile: 'Dockerfile.pnpm', target: 'home' },
            { dockerfile: 'Dockerfile.postgres', tag: 'postgres' }
          ]
    # See: https://github.com/docker/build-push-action
    steps:
      - name: Generate Docker tags
        uses: docker/metadata-action@v5
        with:
          images: 'hackbu/${{ matrix.image.target || matrix.image.tag }}'
          tags: type=sha
          flavor: latest=true
      # Docs: https://github.com/docker/setup-qemu-action
      - name: 'Setup QEMU to emulate other platforms'
        uses: 'docker/setup-qemu-action@v3'
      # Docs: https://github.com/docker/setup-buildx-action
      - name: 'Setup Docker Buildx'
        uses: 'docker/setup-buildx-action@v3'
      # Docs: https://github.com/docker/login-action
      # TODO: make HackBU account
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      - name: 'Build and push'
        uses: 'docker/build-push-action@v5'
        with:
          file: './docker/${{ matrix.image.dockerfile }}'
          target: '${{ matrix.image.target }}'
          platforms: 'linux/amd64,linux/arm64'
          # TODO
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.tags }}
