name: 'Build and Deploy'
on:
  push:
    branches:
      - 'main'
jobs:
  build_deploy:
    runs-on: 'ubuntu-22.04'
    # See: https://github.com/docker/build-push-action
    steps:
      # Docs: https://github.com/docker/setup-qemu-action
      - name: 'Setup QEMU to emulate other platforms'
        uses: 'docker/setup-qemu-action@v3'
      # Docs: https://github.com/docker/setup-buildx-action
      - name: 'Setup Docker Buildx'
        uses: 'docker/setup-buildx-action@v3'
      # Docs: https://github.com/docker/login-action
      # TODO: make HackBU account
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      - name: 'Build and push'
        uses: 'docker/build-push-action@v5'
        with:
          context: '.'
          file: '{{context}}/Dockerfile.pnpm'
          platforms: 'linux/amd64,linux/arm64'
          # TODO
          push: 'false'
